services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: agentic-rag-postgres
    environment:
      POSTGRES_USER: raguser
      POSTGRES_PASSWORD: ragpass123
      POSTGRES_DB: agentic_rag_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - rag-network

  neo4j:
    image: neo4j:5.28.1-community
    container_name: agentic-rag-neo4j
    environment:
      NEO4J_AUTH: neo4j/password123
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
    ports:
      - "7474:7474"  # Browser
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
    networks:
      - rag-network

  ollama:
    image: ollama/ollama:latest
    container_name: agentic-rag-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - rag-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  app:
    build: .
    container_name: agentic-rag-app
    depends_on:
      - postgres
      - neo4j
      - ollama
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://raguser:ragpass123@postgres:5432/agentic_rag_db
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: password123
      LLM_BASE_URL: http://ollama:11434/v1
      EMBEDDING_BASE_URL: http://ollama:11434/v1
    ports:
      - "8058:8058"
    volumes:
      - ./documents:/app/documents
      - ./big_tech_docs:/app/big_tech_docs
      - ./.env:/app/.env
    networks:
      - rag-network
    command: python -m agent.api

volumes:
  postgres_data:
  neo4j_data:
  ollama_data:

networks:
  rag-network:
    driver: bridge